<?php
/**
 * Injecte un Array $datas_annuaire, contenant l'ensemble de l'annuaire
 */

$datas_annuaire = [
    'shaarli_techs' => [
        'cat_name' => 'Shaarli | Techs',
        'cat_id' => 'shaarli_techs',
        'links' => [
            [
                'url' => 'https://lehollandaisvolant.net',
                'name' => 'Le Hollandais Volant',
                'desc' => 'Blog du Hollandais Volant',
                'rss_type' => 'rss',
                'rss' => 'https://lehollandaisvolant.net/rss.php',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://sebsauvage.net/links/',
                'name' => 'Sebsauvage',
                'desc' => 'Liens en vrac de sebsauvage',
                'rss_type' => 'rss',
                'rss' => 'https://sebsauvage.net/links/?do=rss',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://ecirtam.net/links/',
                'name' => 'Oros',
                'desc' => 'Liens en vrac d\'Oros',
                'rss_type' => 'rss',
                'rss' => 'https://ecirtam.net/links/?do=rss',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://ecirtam.net/opennews/',
                'name' => 'OpenNews',
                'desc' => 'Soumettre et diffuser ses liens - ouvert à tous',
                'rss_type' => 'rss',
                'rss' => 'https://ecirtam.net/opennews/?do=rss',
                'cats' => ['shaarli_techs', 'shaarli', 'news'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://dukeart.netlib.re/links/',
                'name' => 'Duke',
                'desc' => 'Liens en vrac de Duke',
                'rss_type' => 'rss',
                'rss' => 'https://dukeart.netlib.re/links/?do=rss',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://shaarli.duraffort.fr/',
                'name' => 'Du',
                'desc' => 'Les liens Du',
                'rss_type' => 'atom',
                'rss' => 'https://shaarli.duraffort.fr/?do=atom',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://ecirtam.net/shaarlirss/',
                'name' => 'Communauté shaarli',
                'desc' => 'Agrégation de plusieurs flux Shaarli libres et indépendants du web',
                'rss_type' => 'rss',
                'rss' => 'https://ecirtam.net/shaarli-api/latest?format=rss',
                'cats' => ['communautes_techs', 'shaarli'],
                'keywords' => ['tech', 'news'],
                'desc_long' => [''],
            ],
            [
                'url' => 'http://osd.ovh/shaarli/',
                'name' => 'Osd',
                'desc' => 'Les liens d\'Osd' ,
                'rss_type' => 'rss',
                'rss' => 'http://osd.ovh/shaarli/feed/rss?',
                'cats' => ['shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://eric.bugnet.fr/shaarli/',
                'name' => 'Eric Bugnet',
                'desc' => 'Les liens d\'Eric',
                'rss_type' => 'rss',
                'rss' => 'https://eric.bugnet.fr/shaarli/?do=rss',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://chezsoi.org/shaarli/',
                'name' => 'Chezsoi',
                'desc' => 'Les liens de chezsoi.org',
                'rss_type' => 'atom',
                'rss' => 'https://chezsoi.org/shaarli/?do=atom',
                'cats' => ['shaarli_techs', 'shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://www.djan-gicquel.fr/spip.php?page=fluxcontinu',
                'name' => 'Brèves Djan GICQUEL',
                'desc' => 'Les liens de Djan GICQUEL' ,
                'rss_type' => 'rss',
                'rss' => 'https://www.djan-gicquel.fr/spip.php?page=backend',
                'cats' => ['shaarli'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://links.hoa.ro',
                'name' => 'ArthurHoaro',
                'desc' => 'Les liens d\' ArthurHoaro' ,
                'rss_type' => 'atom',
                'rss' => 'https://links.hoa.ro/feed/atom?',
                'cats' => ['shaarli'],
                'keywords' => ['tech', 'développeur web', 'full stack', 'PHP', 'Symfony', 'JS', 'NodeJS', 'VueJS', 'DevOps', 'Docker', 'Kubernetes', 'Java', 'Python', 'Ruby', 'logiciel libre', 'Shaarli', 'auto-hébergement', 'open source', 'Lyon', 'France', 'télétravail', 'professionnel', 'blog', 'code', 'développement', 'freelance', 'ingénierie logicielle'],
                'desc_long' => [''],
            ],
        ],
    ],
    'shaarli_actus' => [
        'cat_name' => 'Shaarli | Actus',
        'cat_id' => 'shaarli_actus',
        'links' => [
            [
                'url' => 'https://shaarli.mydjey.eu/',
                'name' => 'Mydjey',
                'desc' => 'Le bazar de mydjey',
                'rss_type' => 'atom',
                'rss' => 'https://shaarli.mydjey.eu/?do=atom',
                'cats' => ['shaarli_actus', 'shaarli'],
                'keywords' => ['actus'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://www.mypersonnaldata.eu/shaarli/',
                'name' => 'Lapin Masqué',
                'desc' => 'Les liens du Lapin Masqué',
                'rss_type' => 'rss',
                'rss' => 'https://www.mypersonnaldata.eu/shaarli/?do=rss',
                'cats' => ['shaarli_actus', 'shaarli'],
                'keywords' => ['actus'],
                'desc_long' => [''],
            ],
            [
                'url' => 'http://shaarli.guiguishow.info/',
                'name' => 'GuiGui\'s Show',
                'desc' => 'Les liens de GuiGui',
                'rss_type' => 'rss',
                'rss' => 'http://shaarli.guiguishow.info/?do=rss',
                'cats' => ['shaarli_actus', 'shaarli'],
                'keywords' => ['actus'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://book.knah-tsaeb.org/',
                'name' => 'Knah Tsaeb',
                'desc' => 'Les liens de Knah Tsaeb' ,
                'rss_type' => 'atom',
                'rss' => 'https://book.knah-tsaeb.org/?do=atom',
                'cats' => ['shaarli'],
                'keywords' => ['actus'],
                'desc_long' => [''],
            ],
            [
                'url' => 'http://shaarli.zeseb.fr/?',
                'name' => 'Zeseb',
                'desc' => 'Les liens de Zeseb' ,
                'rss_type' => 'rss',
                'rss' => 'http://shaarli.zeseb.fr/?do=rss',
                'cats' => ['shaarli'],
                'keywords' => ['actus'],
                'desc_long' => [''],
            ],
        ],
    ],
    'sites_techs' => [
        'cat_name' => 'Sites Persos | Techs',
        'cat_id' => 'sites_techs',
        'links' => [
            [
                'url' => 'https://ecirtam.net/',
                'name' => 'Site d\'Oros',
                'desc' => 'Site complet proposant notamment des webservices et flux d\'actualités',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['sites_techs'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://dukeart.netlib.re',
                'name' => 'Site de Duke',
                'desc' => 'Site complet proposant notamment des webservices et api',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['sites_techs'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://eric.bugnet.fr',
                'name' => 'Site d\'Eric bugnet',
                'desc' => 'Blog d\'Eric où il dit ce qu\'il veut en plus de 140 caractères' ,
                'rss_type' => 'rss',
                'rss' => 'https://eric.bugnet.fr/feed/',
                'cats' => ['sites_techs'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://www.djan-gicquel.fr/',
                'name' => 'Site Djan GICQUEL',
                'desc' => 'Blog de Djan GICQUEL Informagicien, crypto-enthousiaste, adorateur des internets 2.0' ,
                'rss_type' => 'rss',
                'rss' => 'https://www.djan-gicquel.fr/spip.php?page=backend',
                'cats' => ['sites_techs'],
                'keywords' => ['tech'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://hoa.ro/fr/blog/',
                'name' => 'Side d\'ArthurHoaro',
                'desc' => 'Blog de ArthurHoaro : Web developer, freelancer, passionate ' ,
                'rss_type' => 'rss',
                'rss' => 'https://hoa.ro/fr/blog/index.xml',
                'cats' => ['sites_techs'],
                'keywords' => ['tech', 'développeur web', 'full stack', 'PHP', 'Symfony', 'JS', 'NodeJS', 'VueJS', 'DevOps', 'Docker', 'Kubernetes', 'Java', 'Python', 'Ruby', 'logiciel libre', 'Shaarli', 'auto-hébergement', 'open source', 'Lyon', 'France', 'télétravail', 'professionnel', 'blog', 'code', 'développement', 'freelance', 'ingénierie logicielle'],
                'desc_long' => [''],
            ],
        ],
    ],
    'blogs_penseurs' => [
        'cat_name' => 'Blogs | Penseurs et Essayistes',
        'cat_id' => 'blogs_penseurs',
        'links' => [
            [
                'url' => 'http://autobiogramm.tuxfamily.org/',
                'name' => 'autobiogramm',
                'desc' => 'Blog d\'un neuro a +',
                'rss_type' => 'rss',
                'rss' => 'http://autobiogramm.tuxfamily.org/rss.xml',
                'cats' => ['blogs_penseurs'],
                'keywords' => ['penseurs'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://jhus.tuxfamily.org/indexdescontenus.html',
                'name' => 'J\'Habite Un Soupir',
                'desc' => 'Blogueuse de vie quotidienne',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['blogs_penseurs'],
                'keywords' => ['penseurs'],
                'desc_long' => [''],
            ],
        ],
    ],
    'communautes_techs' => [
        'cat_name' => 'Forums & Communautés | Techs',
        'cat_id' => 'communautes_techs',
        'links' => [
            [
                'url' => 'https://n-pn.fr/index.php',
                'name' => 'N-pn.fr',
                'desc' => 'Board de la communauté white hat de N-pn',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['sites_techs'],
                'keywords' => ['communautes_techs'],
                'desc_long' => [''],
            ]
        ],
    ],
    'communautes_autres' => [
        'cat_name' => 'Forums & Communautés | Autres',
        'cat_id' => 'communautes_autres',
        'links' => [
            [
                'url' => 'https://www.cactuspro.com/',
                'name' => 'Au Cactus Francophone',
                'desc' => 'Portails communautaire complet dont une encyclopédie collaborative sur l\'univers des plantes grasses et succulentes',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['communautes_autres'],
                'keywords' => ['cactus', 'plantes'],
                'desc_long' => [''],
            ],
        ],
    ],
    'projets' => [
        'cat_name' => 'Projets libres, libristes ou à sources publiques',
        'cat_id' => 'projets',
        'links' => [
            [
                'url' => 'https://www.pluxml.org/',
                'name' => 'PluXml',
                'desc' => 'CMS opensource français et gratuit, sans base de données',
                'rss_type' => 'rss',
                'rss' => 'https://www.pluxml.org/feed/rss',
                'cats' => ['projets'],
                'keywords' => ['cms', 'xml'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://www.tuxfamily.org',
                'name' => 'Tuxfamily.org',
                'desc' => 'Association pour la promotion et la diffusion de contenus libres - hébergements libres gérés par des bénévoles',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['projets'],
                'keywords' => ['hosting', 'hebergement'],
                'desc_long' => [''],
            ],
        ],
    ],
    'services' => [
        'cat_name' => 'Services en ligne utile',
        'cat_id' => 'services',
        'links' => [
            [
                'url' => 'https://gchq.github.io/CyberChef/',
                'name' => 'CyberChef',
                'desc' => 'Outil complet pour la cyber sécurité. Coder/Décoder, Xor, Forensic, Compression, données EXIF...',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['services'],
                'keywords' => ['service', 'xor', 'decode', 'security'],
                'desc_long' => [''],
            ],
            [
                'url' => 'https://oldschooldev.io',
                'name' => 'oldschooldev.io',
                'desc' => 'Service d\'annuaire, offres d\'emplois et partage de flux rss shaarli indépendant...',
                'rss_type' => 'rss',
                'rss' => 'https://oldschooldev.io/feed.php?rss',
                'cats' => ['services', 'annuaire'],
                'keywords' => ['shaarli', 'rss'],
                'desc_long' => [''],
            ],
        ],
    ],
    'photographes' => [
        'cat_name' => 'Blogs | Photographes',
        'cat_id' => 'photographes',
        'links' => [
            [
                'url' => 'http://rijidepot.tuxfamily.org/',
                'name' => 'Lydie Guézengar',
                'desc' => 'Photographe et créatrice de contenu web',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['photographes'],
                'keywords' => ['photographe', 'artistes'],
            ],
        ],
    ],
    'emplois' => [
        'cat_name' => 'Offres d\'Emplois | Tech',
        'cat_id' => 'emplois_tech',
        'links' => [
            [
                'url' => 'https://oldschooldev.io/index.php?categorie5/offres-emplois',
                'name' => 'oldschooldev - Emplois',
                'desc' => 'Offres d\'emplois tech publié sur OldsSchoolDev',
                'rss_type' => 'rss',
                'rss' => 'https://oldschooldev.io/feed.php?rss/categorie005/offres-emplois',
                'cats' => ['emploi'],
                'keywords' => ['tech', 'emploi'],
            ],
        ],
    ],
    'freelances' => [
        'cat_name' => 'Freelances | Dev',
        'cat_id' => 'freelances',
        'links' => [
            [
                'url' => 'https://hoa.ro/',
                'name' => 'ArthurHoaro',
                'desc' => 'Web developer, freelancer, passionate',
                'rss_type' => 'rss',
                'rss' => '',
                'cats' => ['freelances'],
                'keywords' => ['freelances', 'développeur web', 'full stack', 'PHP', 'Symfony', 'JS', 'NodeJS', 'VueJS', 'DevOps', 'Docker', 'Kubernetes', 'Java', 'Python', 'Ruby', 'logiciel libre', 'Shaarli', 'auto-hébergement', 'open source', 'Lyon', 'France', 'télétravail', 'professionnel', 'blog', 'code', 'développement', 'freelance', 'ingénierie logicielle'],
            ],
        ],
    ],


];